spring:
  application:
    name: AuthApp
  profiles:
    active: dev

  # ───── Database (MySQL) ─────
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ssssssssss       # 👈 change this
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ───── JPA / Hibernate ─────
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

# ───── Server ─────
server:
  port: 8082

# ───── JWT ─────
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000       # 24 hours in milliseconds