#Development version of proporties configuration 
server:
   port: 8083

#database connection properties
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/auth_app_yt?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: ssssssssss       # 👈 change this
      driver-class-name: com.mysql.cj.jdbc.Driver

   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
           dialect: org.hibernate.dialect.MySQLDialect
           format_sql: true
      show-sql: true
         

#jpa and hibenate configuration
#testing the another branch sarbeshbranch